version: '3.8'

services:
  app:
    container_name: gemini-api
    image: alqinsidev/gemini-sandbox
    ports:
      - "2701:2701"  # Assuming your Go app listens on port 2701
    depends_on:
      - db
    restart: always
    environment:
      - API_KEY= #use your google project API key (ref: https://makersuite.google.com/app/apikey)
      - APP_PORT=2701
      - MYSQL_HOST=db  # Change to service name 'db' to connect within Docker network
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=supersecurepassword
      - MYSQL_DB_NAME=gemini
      - MIGRATION_PATH=file://app/db/migration/scripts
      - GIN_MODE=release

  db:
    container_name: gemini-db
    image: mysql:latest
    ports:
      - "3306:3306"  # Expose MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: supersecurepassword  # Set MySQL root password
      MYSQL_DATABASE: gemini             # Set the name of the database
      MYSQL_PASSWORD: supersecurepassword        # Set password for the new user (optional)
    volumes:
      - mysql:/var/lib/mysql  # Mount a volume to persist MySQL data
volumes: 
  mysql:
