version: '3.8'

services:
  app:
    container_name: gemini-api
    image: alqinsidev/gemini-sandbox
    ports:
      - "2701:2701"
    depends_on:
      - db
    restart: always
    environment:
      - API_KEY= #use your google project API key (ref: https://makersuite.google.com/app/apikey)
      - APP_PORT=2701
      - MYSQL_HOST=db  
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=supersecurepassword
      - MYSQL_DB_NAME=gemini
      - MIGRATION_PATH=file://app/db/migration/scripts
      - GIN_MODE=release

  db:
    container_name: gemini-db
    image: mysql:latest
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: supersecurepassword
      MYSQL_DATABASE: gemini
      MYSQL_PASSWORD: supersecurepassword
    volumes:
      - mysql:/var/lib/mysql
volumes: 
  mysql:
